version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "32763:80"
      - "7153:443"
      
    environment:
      - "ASPNETCORE_URLS=https://+;http://+"
      - ASPNETCORE_HTTPS_PORTS=7153
      - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssw0rd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx

    volumes:
      - ./docker_appsettings.json:/app/appsettings.json  # Mount local appsettings.json
      - ./videos:/app/videos  # Mount local videos directory
      - ${USERPROFILE}/.aspnet/https:/https/  # Important for HTTPS

    restart: always
